### ISSUE TITLE
pip install -e . fails on master

### ISSUE THREAD

**Issue by sobolevnrm** [Electrostatics/apbs#137]
```
(mmcif) PS: mmcif_pdbx> pip install -e .
Obtaining file:///C:/Users/bake113/OneDrive%20-%20PNNL/Documents/Git/mmcif_pdbx
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\bake113\Anaconda3\envs\mmcif\python.exe' 'C:\Users\bake113\Anaconda3\envs\mmcif\lib\site-packages\pip\_vendor\pep517\_in_process.py' get_requires_for_build_wheel 'C:\Users\bake113\AppData\Local\Temp\tmpnh2l05wl'
       cwd: C:\Users\bake113\OneDrive - PNNL\Documents\Git\mmcif_pdbx
  Complete output (16 lines):
  Traceback (most recent call last):
    File "C:\Users\bake113\Anaconda3\envs\mmcif\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 280, in <module>
      main()
    File "C:\Users\bake113\Anaconda3\envs\mmcif\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "C:\Users\bake113\Anaconda3\envs\mmcif\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "C:\Users\bake113\AppData\Local\Temp\pip-build-env-fuy3wpwi\overlay\Lib\site-packages\setuptools\build_meta.py", line 154, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "C:\Users\bake113\AppData\Local\Temp\pip-build-env-fuy3wpwi\overlay\Lib\site-packages\setuptools\build_meta.py", line 135, in _get_build_requires
      self.run_setup()
    File "C:\Users\bake113\AppData\Local\Temp\pip-build-env-fuy3wpwi\overlay\Lib\site-packages\setuptools\build_meta.py", line 150, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 3, in <module>
      import versioneer
  ModuleNotFoundError: No module named 'versioneer'
  ----------------------------------------
WARNING: Discarding file:///C:/Users/bake113/OneDrive%20-%20PNNL/Documents/Git/mmcif_pdbx. Command errored out with exit status 1: 'C:\Users\bake113\Anaconda3\envs\mmcif\python.exe' 'C:\Users\bake113\Anaconda3\envs\mmcif\lib\site-packages\pip\_vendor\pep517\_in_process.py' get_requires_for_build_wheel 'C:\Users\bake113\AppData\Local\Temp\tmpnh2l05wl' Check the logs for full command output.
ERROR: Command errored out with exit status 1: 'C:\Users\bake113\Anaconda3\envs\mmcif\python.exe' 'C:\Users\bake113\Anaconda3\envs\mmcif\lib\site-packages\pip\_vendor\pep517\_in_process.py' get_requires_for_build_wheel 'C:\Users\bake113\AppData\Local\Temp\tmpnh2l05wl' Check the logs for full command output.
```

**Comment by sobolevnrm** [comment]
@orbeckst and @speleo3 -- I would very much like to ditch versioneer in lieu of the simpler approach I use in, for example, https://github.com/Electrostatics/osmolytes/blob/main/osmolytes/__init__.py

Any concerns?

**Comment by intendo** [comment]
You could fix this problem by adding versioneer to the requirements.txt. NOTE: I am also not a big fan of versioneer. 

There is a newer (and maintained) alternative at [dunamai](https://pypi.org/project/dunamai/) but I have not tried it.

So just hard code the version number in setup.py?

**Comment by sobolevnrm** [comment]
> You could fix this problem by adding versioneer to the requirements.txt. NOTE: I am also not a big fan of versioneer.
> 
> There is a newer (and maintained) alternative at [dunamai](https://pypi.org/project/dunamai/) but I have not tried it.
> 
> So just hard code the version number in setup.py?

That would be my preference -- its much simpler.

**Comment by speleo3** [comment]
Works for me. Didn't know about `importlib.metadata.version` yet, but looks very reasonable.

**Comment by intendo** [comment]
I pushed an update to conf.py so that it uses `importlib.metadata.version` so that you don't have to hardcode the version in the docs or use verioneer or append the path to get to `pdbx.version`.

**Comment by orbeckst** [comment]
No concerns — whatever works.

**Comment by sobolevnrm** [comment]
Great!   I'll work on this tonight.  Thanks.
